# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := move_forward_test    # 这个名字就是测试文件的名字，不需要扩展名
ARDUINO_LIBS := AUnit
include ../../../../Documents/Arduino/Libraries/EpoxyDuino/EpoxyDuino.mk